import type { GitHubSnapshot, Student, Team } from '@/types'

export const fixtureStudents: Student[] = [
  { github: 'rahul', name: 'Rahul Sharma', team: 'phoenix', role: 'developer', interests: ['React'] },
  { github: 'gauri', name: 'Gauri Deshpande', team: 'phoenix', role: 'developer', interests: ['Git'] },
  { github: 'om', name: 'Om Patil', team: 'ashes', role: 'developer', interests: ['Backend'] },
  { github: 'lina', name: 'Lina Fernandes', team: 'atlas', role: 'developer', interests: ['UI'] },
  { github: 'arnav', name: 'Arnav Bhatt', team: 'beacon', role: 'developer', interests: ['Backend'] },
]

export const fixtureTeams: Team[] = [
  { id: 'phoenix', name: 'Phoenix', members: [], category: 'general' },
  { id: 'ashes', name: 'Ashes', members: [], category: 'general' },
  { id: 'atlas', name: 'Atlas', members: [], category: 'general' },
  { id: 'beacon', name: 'Beacon', members: [], category: 'general' },
]

export const fixtureSnapshot: GitHubSnapshot = {
  repository: {
    name: 'git-real-playground',
    fullName: 'org/git-real-playground',
    description: 'fixture',
    defaultBranch: 'main',
    htmlUrl: 'https://github.com/org/git-real-playground',
    openIssues: 1,
  },
  contributors: [
    { login: 'rahul', avatarUrl: 'https://example.com/rahul.png', htmlUrl: 'https://github.com/rahul', contributions: 2 },
    { login: 'gauri', avatarUrl: 'https://example.com/gauri.png', htmlUrl: 'https://github.com/gauri', contributions: 1 },
  ],
  branches: [
    { name: 'main', sha: 'aaa', protected: true },
    { name: 'feat/list', sha: 'bbb', protected: false },
    { name: 'feat/prod', sha: 'ccc', protected: false },
  ],
  commits: [
    {
      sha: 'c1',
      message: 'feat: list',
      authorLogin: 'rahul',
      authorName: 'Rahul',
      date: '2026-08-21T10:00:00.000Z',
      htmlUrl: 'https://example.com/c1',
    },
    {
      sha: 'c2',
      message: 'feat: tokens',
      authorLogin: 'gauri',
      authorName: 'Gauri',
      date: '2026-08-21T11:00:00.000Z',
      htmlUrl: 'https://example.com/c2',
    },
    {
      sha: 'c3',
      message: 'feat: prod',
      authorLogin: 'om',
      authorName: 'Om',
      date: '2026-08-21T12:00:00.000Z',
      htmlUrl: 'https://example.com/c3',
    },
  ],
  pullRequests: [
    {
      number: 14,
      title: 'Add list',
      body: '',
      state: 'open',
      merged: false,
      draft: false,
      author: 'rahul',
      head: 'feat/list',
      base: 'main',
      createdAt: '2026-08-21T10:30:00.000Z',
      updatedAt: '2026-08-21T13:00:00.000Z',
      mergedAt: null,
      htmlUrl: 'https://example.com/14',
      requestedReviewers: ['gauri'],
      changedFiles: 3,
      additions: 10,
      deletions: 1,
      reviews: [
        {
          id: 1,
          reviewer: 'gauri',
          state: 'APPROVED',
          submittedAt: '2026-08-21T12:00:00.000Z',
          body: 'lgtm',
        },
        {
          id: 2,
          reviewer: 'lina',
          state: 'COMMENTED',
          submittedAt: '2026-08-21T12:30:00.000Z',
          body: 'nits',
        },
      ],
      ciStatus: 'pass',
    },
    {
      number: 21,
      title: 'Prod stub',
      body: '',
      state: 'open',
      merged: false,
      draft: false,
      author: 'om',
      head: 'feat/prod',
      base: 'main',
      createdAt: '2026-08-21T12:10:00.000Z',
      updatedAt: '2026-08-21T13:10:00.000Z',
      mergedAt: null,
      htmlUrl: 'https://example.com/21',
      requestedReviewers: [],
      changedFiles: 1,
      additions: 8,
      deletions: 0,
      reviews: [],
      ciStatus: 'fail',
    },
  ],
  issues: [
    {
      number: 3,
      title: 'Add team filtering',
      state: 'closed',
      author: 'gauri',
      labels: ['feature-lab'],
      createdAt: '2026-08-20T10:00:00.000Z',
      closedAt: '2026-08-21T09:00:00.000Z',
      htmlUrl: 'https://example.com/issues/3',
      isPullRequest: false,
    },
  ],
  workflowRuns: [
    {
      id: 1,
      name: 'CI',
      status: 'completed',
      conclusion: 'success',
      headBranch: 'feat/list',
      event: 'pull_request',
      htmlUrl: 'https://example.com/run/1',
      createdAt: '2026-08-21T11:00:00.000Z',
      pullRequestNumbers: [14],
    },
    {
      id: 2,
      name: 'CI',
      status: 'completed',
      conclusion: 'failure',
      headBranch: 'feat/prod',
      event: 'pull_request',
      htmlUrl: 'https://example.com/run/2',
      createdAt: '2026-08-21T13:00:00.000Z',
      pullRequestNumbers: [21],
    },
  ],
  releases: [
    {
      id: 1,
      tagName: 'v0.1.0',
      name: 'seed',
      draft: false,
      prerelease: false,
      publishedAt: '2026-08-20T00:00:00.000Z',
      htmlUrl: 'https://example.com/releases/1',
      author: 'instructor',
    },
  ],
  fetchedAt: '2026-08-21T18:00:00.000Z',
  rateLimitRemaining: 4000,
}
