export const summary = 'Why does this pointless-looking line exist?'

export function build(scenario) {
  const { write, commit, mission } = scenario

  write('README.md', '# Upload Service\n')
  write(
    'upload.js',
    `export async function upload(file, client) {
  const url = await client.createUploadUrl(file.name)
  return client.put(url, file)
}
`,
  )
  commit('feat: add file upload')

  write(
    'upload.js',
    `export async function upload(file, client) {
  const url = await client.createUploadUrl(file.name)
  return client.put(url, file)
}

export function contentTypeFor(name) {
  if (name.endsWith('.png')) return 'image/png'
  if (name.endsWith('.pdf')) return 'application/pdf'
  return 'application/octet-stream'
}
`,
  )
  commit('feat: detect content type from file extension')

  write(
    'upload.js',
    `const UPLOAD_URL_SETTLE_MS = 250

export async function upload(file, client) {
  const url = await client.createUploadUrl(file.name)
  await new Promise((resolve) => setTimeout(resolve, UPLOAD_URL_SETTLE_MS))
  return client.put(url, file)
}

export function contentTypeFor(name) {
  if (name.endsWith('.png')) return 'image/png'
  if (name.endsWith('.pdf')) return 'application/pdf'
  return 'application/octet-stream'
}
`,
  )
  scenario.git(['add', '-A'])
  scenario.git([
    'commit',
    '-m',
    `fix: wait 250ms before PUTting to a fresh upload URL

Roughly one upload in fifty was failing with 403 SignatureDoesNotMatch, only
in production, only for the first upload after a cold start. It was never
reproducible locally.

The signed URL is generated by one node in the storage cluster and validated
by whichever node receives the PUT. Propagation between them is not
instantaneous. If we PUT immediately after createUploadUrl returns, the
receiving node may not know about the signature yet and rejects it as invalid.

250ms was measured against the 99.9th percentile of observed propagation
delay over two weeks of logs. 100ms still failed occasionally. 500ms was
comfortably safe and made bulk uploads noticeably slower.

This looks like a pointless sleep. It is not. Removing it brings back a
failure that only appears under production load and looks like an
authentication bug rather than a timing one.

If the storage provider ever gives us a synchronous signature API, delete
this and the constant with it.

Refs: INC-2291`,
  ])

  write(
    'upload.js',
    `const UPLOAD_URL_SETTLE_MS = 250

export async function upload(file, client) {
  const url = await client.createUploadUrl(file.name)
  await new Promise((resolve) => setTimeout(resolve, UPLOAD_URL_SETTLE_MS))
  return client.put(url, file, { contentType: contentTypeFor(file.name) })
}

export function contentTypeFor(name) {
  if (name.endsWith('.png')) return 'image/png'
  if (name.endsWith('.pdf')) return 'application/pdf'
  return 'application/octet-stream'
}

export function isTooLarge(file, limitBytes = 10 * 1024 * 1024) {
  return file.size > limitBytes
}
`,
  )
  commit('feat: send content type and add a size guard')

  write(
    'upload.js',
    `const UPLOAD_URL_SETTLE_MS = 250

export async function upload(file, client) {
  if (isTooLarge(file)) {
    throw new Error('File is larger than the 10MB limit')
  }
  const url = await client.createUploadUrl(file.name)
  await new Promise((resolve) => setTimeout(resolve, UPLOAD_URL_SETTLE_MS))
  return client.put(url, file, { contentType: contentTypeFor(file.name) })
}

export function contentTypeFor(name) {
  if (name.endsWith('.png')) return 'image/png'
  if (name.endsWith('.pdf')) return 'application/pdf'
  return 'application/octet-stream'
}

export function isTooLarge(file, limitBytes = 10 * 1024 * 1024) {
  return file.size > limitBytes
}
`,
  )
  commit('feat: reject oversized files before requesting a URL')

  mission(`# Mission — find out why a line exists before you delete it

## The situation

You have been asked to speed up uploads. You open \`upload.js\` and find this:

\`\`\`js
await new Promise((resolve) => setTimeout(resolve, UPLOAD_URL_SETTLE_MS))
\`\`\`

A quarter of a second of doing nothing, in the middle of the upload path. No
comment. Deleting it is an easy 250ms win.

Before you do: somebody wrote that line on purpose.

## Your mission

Find out who added it, when, and above all **why** — then decide whether to
delete it.

## You may need

\`\`\`bash
git blame upload.js
\`\`\`

That gives you a commit SHA for every line. Find the SHA for the sleep, then:

\`\`\`bash
git show <sha>
\`\`\`

Read the whole message, not just the subject line.

## Done when

You can answer, without guessing:

- What symptom did this line fix?
- Why did it never reproduce on a developer machine?
- Why 250 milliseconds and not 100, or 500?
- Under what future condition would it be safe to remove?

## Worth noticing

The code could not have told you any of that. There is nothing you could add to
that line as a comment that would carry two weeks of production log analysis.
The commit message could, and did.

This is the argument for writing commit messages that explain *why*. The diff
already shows what changed. The reasoning only survives if somebody writes it
down, and the commit is the one place attached to the exact lines it explains.

## One more thing

The command is called \`blame\`, which is an unfortunate name. Nothing about
this is anybody's fault. You are doing archaeology, not building a case.

Practically: \`git blame\` on a line somebody else wrote, followed by asking them
about it, is one of the fastest ways to learn a codebase.
`)

  return {
    story: [
      'A 250ms sleep sitting in the middle of an upload function, with no comment.',
      'It looks like an easy performance win. Find out why it is there first.',
    ],
    firstMoves: ['cat upload.js', 'git blame upload.js'],
  }
}
